server:
  port: 8083

spring:
  application:
    name: lbn-recommend-service
  config:
    import:
      - optional:nacos:lbn-recommend-service.yml
  cloud:
    nacos:
      server-addr: "${LBN_NACOS_ADDR:127.0.0.1:8848}"
      discovery:
        server-addr: "${LBN_NACOS_ADDR:127.0.0.1:8848}"
      config:
        server-addr: "${LBN_NACOS_ADDR:127.0.0.1:8848}"
        file-extension: yml
  data:
    redis:
      host: ${LBN_REDIS_HOST:127.0.0.1}
      port: ${LBN_REDIS_PORT:6379}
  rabbitmq:
    host: ${LBN_RABBIT_HOST:127.0.0.1}
    port: ${LBN_RABBIT_PORT:5672}
    username: ${LBN_RABBIT_USER:guest}
    password: ${LBN_RABBIT_PASSWORD:guest}

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 10000
