server:
  port: 8083

spring:
  application:
    name: lbn-recommend-service
  config:
    import:
      - optional:nacos:lbn-recommend-service.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 10000
